# 1. create a list of random number of dicts (from 2 to 10)
import random
import string

dictList = []
for i in range(random.randint(2,10)): # random number of dictionaries (from 2 to 10)
    size = random.randint(1,5)    # random dictionary size (for example, 1-5)
    keys = random.sample(string.ascii_lowercase,size)  # random letters
    values = (random.randint(0,100) for i in range(size))  # random number for values
    oneDict = dict(zip(keys,values))                      # create dictionary from tuples, that generated by iterator zip
    dictList.append(oneDict)                              # add it to the list
print(dictList)

#2 get previously generated list of dicts and create one common dict
finalDict = {}
checkedList = [] # list for already checked keys
# loop for each dictionary
for i in range(len(dictList)):
    current_list = dictList[i]
    # loop for each key
    for current_key, current_value in current_list.items():
        final_key = current_key
        final_value = current_value
        checked_key = current_key
        # loop for comparing value of current key with other values of the rest dictionaries
        for i_nextList in range(i+1, len(dictList)):
            try:
                # if dicts have same key, we will take max value, and rename key with dict number with max value
                tmp_value = dictList[i_nextList][current_key]
                if tmp_value > current_value:
                    final_key = current_key + '_' + str(i_nextList+1)
                    final_value = tmp_value
            except:
                pass
        # avoiding double-check already checked keys
        if checked_key not in checkedList:
            finalDict[final_key] = final_value
        checkedList.append(checked_key)
print(finalDict)
